### ISSUE TITLE
Log file for indent

### ISSUE THREAD

**Issue by cereda** [cereda/arara#100]
https://github.com/cereda/arara/blob/79092ab4302168913852f108d4ef82cdccfceb82/rules/indent.yaml#L42

@cmhughes Chris, I noticed this line and I think it does not look correct. I think it should be:

```
@{[ '-g', parameters.logfile ]}
```

Or something along those lines (untested). Thoughts?

**Comment by cmhughes** [comment]
Your proposal sounds good to me, although I don't have a way to test it.

latexindent can be called with, for example,

latexindent.pl -g=mylogfile.log

**Comment by cereda** [comment]
Nice, Chris! Should I adopt the `=` sign or leave it as two parameters, as it is?

**Comment by cmhughes** [comment]
There should be no need for the = sign, as we can also call it simply as

latexindent.pl -g mylogfile.log

Thanks for all of your work here!

**Comment by cereda** [comment]
Done, Chris! Thank you!

**Comment by cmhughes** [comment]
Thanks, Paulo, I appreciate your work on this :)
