### ISSUE TITLE
Clean rule and subdirectories

### ISSUE THREAD

**Issue by zoqaeski** [cereda/arara#107]
A useful feature that could be added to the clean rule is a means to select subdirectory from which to clean files. As an example, I use TikZ external *a lot*, and to avoid clutter in my main directory I always render the images in `tikz/`, producing a bunch of auxiliary files as well as the standalone image. Sometimes I want to clean out that directory as well, so a clean rule along the lines of
```
% arara: clean: { subdirectory: 'tikz', extensions: [ aux, log ] }
```
would be extremely useful, especially given that [the `xsim` package does not play nicely with TikZ externalize](https://github.com/cgnieder/xsim/issues/32), and generates potentially hundreds of auxiliary files that are never used.

The only catch is that the files in the `tikz` directory are going to have generated filenames that cannot be predicted from the basename, so some sort of wildcard processing may be necessary. To prevent this rule escaping and deleting things it shouldn't, the subdirectory parameter should throw an error if it contains an absolute path or `../`.

**Comment by cereda** [comment]
Hello!

It sounds like a very interesting idea, thank you! I will take a closer look later on (I am currently in a marathon writing the user manual, finally). Also, thanks for the example posted in Clemens' `xsim` repository, it gave me a clear view of the proposed scenario.

Regarding the wildcard processing, if I recall correctly, subshells are a bit restricted on this matter, but I can easily inject programming code in the rule to spot the correct files. :wink: I will report soon.

Thanks!

**Comment by adimajo** [comment]
Hi! I'm currently in the process of writing my PhD thesis, so that I have e.g. Chapters as .tex files, lots of tikz figures (that make up animations) in separate .tex files (as mentioned by @zoqaeski), ... in subdirectories which .aux files are not cleaned by the clean rule.

This message just to state again that this feature would be nice to have!

Thanks for all the good work!

**Comment by cereda** [comment]
Holy cow, I completely forgot about this issue! Thanks @adimajo for bringing it up!

The new version of `arara` has some new features than can be used for this very purpose. I am on a hurry right now, but I will propose a solution later on today! Sorry for the delay! :wink:

**Comment by cereda** [comment]
A possible solution is presented as follows. Consider the `remove` rule (version 1):

```yaml
!config
identifier: remove
name: Remove
authors:
- Paulo Cereda
commands:
- name: The removal feature
  command: >
    @{
      entries = listFilesByExtensions(
                    toFile(directory),
                    extensions,
                    recursive);
      prefix = [];
        if (isUnix()) {
            prefix = [ 'rm', '-f' ];
        }
        else {
            prefix = [ 'cmd', '/c', 'del' ];
        }
        removals = [];
        for (entry : entries) {
            removals.add(getCommand(prefix,
                     entry.getCanonicalPath()));
        }
        return removals;
    }
arguments:
- identifier: directory
  flag: >
    @{
        return parameters.directory
    }
  default: '.'
- identifier: recursive
  flag: >
    @{
        return isTrue(parameters.recursive)
    }
  default: >
    @{
        return false
    }
- identifier: extensions
  flag: >
    @{
        if (!isList(parameters.extensions)) {
            throwError('I was expecting a list!');
        }
        return parameters.extensions;
    }
  required: true
```

There are three possible parameters for this rule:

- `extensions`, mandatory, expects a list: as the name indicates, this parameter takes a list of file extensions without the leading dot. For instance:
    ```tex
    % arara: remove: { extensions: [ aux, log ] }
    ```
    The previous example will remove `aux` and `log` files from the current directory, _without_ considering subdirectories.
- `directory`, optional, defaults to `.` (current directory): this parameter refers to the directory in which the file search will be performed. If omitted, the current directory is used as reference. If you use relative paths (which is the most common scenario), make sure to invoke `arara` from the correct top level directory (this can be arranged in the rule with some modifications). For instance:
    ```tex
    % arara: remove: { extensions: [ aux, log ], directory: chapters }
    ```
    The previous example will perform the search within the relative `chapters` directory, ignoring subdirectories. Only this directory will be inspected.

- `recursive`, optional, defaults to `false`: by default, the rule only searches files in the provided directory. If you want to extend the search to subdirectories as well, set this parameter to a natural boolean denoting `true`. For instance:
    ```tex
    % arara: remove: { extensions: [ aux, log ], recursive: yes }
    ```
    The previous example will search for file matching the extensions from the current directory and the entire subdirectory structure as well. Beware this might take time depending on the tree to be inspected.

Observe that this rule searches for files matching the extensions. If you want to search for patterns, like names and wildcards, we have version 2 of `remove` as follows:

```yaml
!config
identifier: remove
name: Remove
authors:
- Paulo Cereda
commands:
- name: The removal feature
  command: >
    @{
      entries = listFilesByPatterns(
                    toFile(directory),
                    patterns,
                    recursive);
      prefix = [];
        if (isUnix()) {
            prefix = [ 'rm', '-f' ];
        }
        else {
            prefix = [ 'cmd', '/c', 'del' ];
        }
        removals = [];
        for (entry : entries) {
            removals.add(getCommand(prefix,
                     entry.getCanonicalPath()));
        }
        return removals;
    }
arguments:
- identifier: directory
  flag: >
    @{
        return parameters.directory
    }
  default: '.'
- identifier: recursive
  flag: >
    @{
        return isTrue(parameters.recursive)
    }
  default: >
    @{
        return false
    }
- identifier: patterns
  flag: >
    @{
        if (!isList(parameters.patterns)) {
            throwError('I was expecting a list!');
        }
        return parameters.patterns;
    }
  required: true
```

Note that `extensions` is now replaced by `patterns`:

- `patterns`, mandatory, expects a list: this parameter, as the name indicates, takes a list of file patterns. You can use `*` and `?` wildcards. Please note that this is _not_ a regex search. For instance:
    ```tex
    % arara: remove: { extensions: [ '*.aux', '*.log' ] }
    ```
    The previous example is semantically the same presented with the first version of `remove`. Note the use of `*` as the wildcard element.

Please refer to the `arara` manual for more info on the used methods, as well as how to create a project-based configuration file and run custom rules. :wink:

**Comment by adimajo** [comment]
Wow, very impressive!

I used the 2nd proposed version, for the simple reason that package `minitoc` creates files `*.mtc0`, `*.mtc1`, ...

Works like a charm!

If I may, your last example seems wrong: 
> Note that `extensions` is now replaced by `patterns`
> `% arara: remove: { extensions: [ '*.aux', '*.log' ] }`

Which should be: `% arara: remove: { patterns: [ '*.aux', '*.log' ] }`

**Comment by cereda** [comment]
@adimajo oopsie,  my bad! I just fixed the comment, thanks for the pointer. :wink:

All the best!

**Comment by TheTeXnician** [comment]
In version 5 files are resolved against the working directory, so you can use `clean` with a `files` array with `subdirectory/foo.ext` and it will delete from the subdirectory. Please note, that wildcards are unsupported (design decision). We are working on an extended rule description language for version 6 where we aim to include support for that.

**Comment by raedma** [comment]
See an update for arara 6.0.0: https://gitlab.com/islandoftex/arara/-/issues/67#note_538582364

**Comment by realkrantz** [comment]
I get this ERROR MSG: 
```
I could not evaluate the flag expression of one of the arguments.
This part is quite tricky, since it involves aspects of the
underlying expression language. I will do my best to help you in
any way I can. There are more details available on this
exception:

DETAILS ---------------------------------------------------------
[Error: isTrue(parameters.recursive): It looks like "@{
   
return false
}" is not a valid boolean value. This should be an
easy fix. Make sure to use a valid string that represents boolean
values (yes and no, true and false, 1 and 0, and on and
off).]
[Near : {... @{ ....}]
             ^
[Line: 1, Column: 1]
```
