### ISSUE TITLE
TexIndy: unresolvable property or identifier: debug

### ISSUE THREAD

**Issue by bonanza123** [cereda/arara#111]
I'm running arara 4.0 rev 1 and have the following arara chain in my tex file:

```
% arara: lualatex: { synctex: on, shell: true, draft: true, interaction: nonstopmode }
% arara: biber
% arara: makeglossaries
% arara: texindy
% arara: lualatex: { synctex: on, shell: true, draft: true, interaction: nonstopmode }
% arara: lualatex: { synctex: on, shell: true, interaction: nonstopmode }
```

And this gives me

```
[Error: unresolvable property or identifier: debug]
[Near : {...
d('texindy', quiet, debug, markup, modules, ....}]
              
                  ^
[Line: 6, Column: 41]
```

Is that an arara internal issue or due to my setup?

For completeness: I'm running archlinux (with `arara-git` installed) and calling arara from within texstudio via ` arara-git -v -l "mydocument".tex`

**Comment by cereda** [comment]
Hello!

It's an error in the rule. I also spotted the same issue in `xindy` as well. Thank you! I already fixed the rules in the repository and will submit a patch to CTAN as soon as possible!

All the best!

**Comment by cereda** [comment]
By the way, I don't know how to update your version. Perhaps @pat-s can help us? :wink:

**Comment by bonanza123** [comment]
Thanks, works now (I build directly from git again)!

**Comment by cereda** [comment]
Glad to hear it's working! I already submitted the fix to CTAN. Thank you!

**Comment by pat-s** [comment]
> Thanks, works now (I built directly from git again)!

Right, just re-install :+1:

**Comment by cmhughes** [comment]
I think there might be a similar error in indent.yaml

**Comment by cereda** [comment]
@cmhughes indeed, fixed and will submit yet another patch. :wink:

**Comment by cmhughes** [comment]
Ace, many thanks!

**Comment by cereda** [comment]
Patch submitted to CTAN!

**Comment by cereda** [comment]
CTAN poked me back! The new version will be deployed in a day or two, then we will hit TeX Live.
