### ISSUE TITLE
Could not find goal 'assembly' in plugin org.apache.maven.plugins:maven-assembly-plugin:3.1.0

### ISSUE THREAD

**Issue by pat-s** [cereda/arara#113]
When building from `master`.

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.120 s
[INFO] Finished at: 2018-08-15T11:52:35+02:00
[INFO] Final Memory: 7M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'assembly' in plugin org.apache.maven.plugins:maven-assembly-plugin:3.1.0 among available goals help, single -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException

```
npm: 6.3.0
nodejs: 10.8.0

This seems related: https://github.com/sharispe/slib/pull/53/files

**Comment by cereda** [comment]
Does this work?

```
mvn compile assembly:single
```

**Comment by cereda** [comment]
If I recall correctly, the `assembly:assembly` goal was removed in newer versions of the `maven-assembly-plugin` plugin, so the updated compilation chain needs to be `compile` first and then `assembly:single`.

**Comment by pat-s** [comment]
Looks good! Thanks! :duck:

**Comment by cereda** [comment]
Yay, glad it worked! :duck:

**Comment by pat-s** [comment]
@cereda Even though it built successfully, I now get:

`Error: Could not find or load main class com.github.cereda.arara.Arara`

But this maybe related to some packaging on Arch (but I'm not sure yet).
If you have an idea what might be the issue, let me know. I'll take a closer look later.

**Comment by cereda** [comment]
If you run `mvn assembly:single` without `compile`, Maven gives this warning:

```
[WARNING] Cannot include project artifact: com.github.cereda:arara:jar:4.0;
it doesn't have an associated file or directory.
```

And when I try to run the resulting `.jar` file:

```
LANG=C java -jar target/arara-4.0-jar-with-dependencies.jar 
Error: Could not find or load main class com.github.cereda.arara.Arara
```

We have to run `mvn compile assembly:single` in order to work. Either together or in two separate steps, like:

```
mvn compile
mvn assembly:single
```

**Comment by shoahaoliu** [comment]
Thanks！This fixes the problem  I've been having.

**Comment by liuwz** [comment]
nice!
