### ISSUE TITLE
Pay David Carlisle $10

### ISSUE THREAD

**Issue by keeferrourke** [cereda/arara#116]
I'm opening this issue because I am concerned that it has been 4 years, but @cereda has yet to pay back David Carlisle according to the note left in the code base [here](https://github.com/cereda/arara/blame/master/application/src/main/java/com/github/cereda/arara/Arara.java#L202).

> @cereda : Nothing to see here. :) 

Oh I do see sir. I do see.

**Comment by davidcarlisle** [comment]
Perhaps a pull request changing that 10 to 100 is in order.

**Comment by keeferrourke** [comment]
@davidcarlisle I'll leave that up to you :)

**Comment by cereda** [comment]
OH NO

**Comment by cereda** [comment]
A payment is in progress to rectify this issue. :duck:

**Comment by davidcarlisle** [comment]
really? ducks have no sense:-)
