### ISSUE TITLE
Update to indent.yaml with -r switches

### ISSUE THREAD

**Issue by cmhughes** [cereda/arara#123]
Hello Paulo and team!
Thanks for your great work on the `arara` project :)

Following https://github.com/cmhughes/latexindent.pl/pull/169, I wondered if I could request an update to the [`indent.yaml`](https://github.com/cereda/arara/blob/master/rules/indent.yaml) rule for `latexindent.pl`

Explicitly, `latexindent.pl` has 3 new switches: 
- `-r|replacement`
- `-rv|replacementrespectsverb`
- `-rr|onlyreplacement`

They're all related to replacements, so perhaps you'd prefer to have just one new `arara` option with three sub-options...? Or perhaps three new `arara` options? Very happy to be guided by what you think would be natural. 

Thanks again,
Chris (cmhughes)

**Comment by cereda** [comment]
Hi Chris!

Surely, let us update the rule. :wink: I'd personally favour an option with three possible values. How about:

Directive key: `replacement`
Possible values:
- `full` (semantically equivalent to `-r`), does a full replacement.
- `noverb` (semantically equivalent to `-rv`), respects verbatim environments, is this correct?
- `only`, I have no idea of what means. :wink: 

It's very easy to implement this new option, we just need to think of good values and a nice description of what they do, so I can update both rule and manual. :wink: 

Cheerio!

Paulo

**Comment by cmhughes** [comment]
Thanks, Paulo, that sounds great!

For the 'only' option, you could also call it 'noindent', but either is great with me.

Thanks so much :)
Best
Chris

**Comment by cereda** [comment]
Great, Chris! I will try to work on this update during the weekend! I will stick with `noindent`, it sounds better, I guess. :wink: If it is not too much trouble, could you help me with a brief description of what each option does? Then I can update the manual more easily...

Thank you!

**Comment by cmhughes** [comment]
Thanks, Paulo! 

How about the following:

- the *full* version performs indentation and replacements, not
	       respecting verbatim code blocks;
- the *noverb* version performs indentation and replacements, and
	       \emph{will} respect verbatim code blocks;
- the *noindent* version will \emph{not} perform indentation,  and will perform replacements not respecting verbatim code blocks.
 

I hope this sounds ok, do let me know if you need anything else.
All the best
Chris

**Comment by cereda** [comment]
Ace, Chris! I will update the rule and manual as soon as possible. Thank you! :wink:

**Comment by cmhughes** [comment]
Thanks so much, Paulo, that's wonderful:) there's no immediate rush, but I
certainly appreciate your time on it :)

**Comment by cereda** [comment]
Done! I will soon update the new pack to CTAN! :wink:

**Comment by cmhughes** [comment]
Great, thanks so much!
