### ISSUE TITLE
Working directory support for all engines

### ISSUE THREAD

**Issue by cereda** [cereda/arara#127]
Friends,

Consider the following directory structure:

```
.
├── a
│   └── bar.tex
└── foo.tex
```

We are currently located at `.`, i.e, the _root_ of our project. Let's say we want to compile `bar.tex` from `foo.tex`. The typical directive would be (inside `foo.tex`, of course):

```tex
% : arara: pdftex: { files: [ 'a/bar.tex' ] }
...
```

However, when calling

```bash
$ arara foo.tex
```

our tool will fail. The reason for such failure is that the `file` reference used in all of our engine rules (and probably throughout the majority of our other rules) resort to the file name, meaning that

```java
file == 'bar.tex'   // true
file == 'a/bar.tex' // false
```

Since we are a bunch of clever clogs (sorry, Peppa Pig influence), we have predicted this situation by creating yet another pointer, but this time, a powerful one: the `reference` variable. This one resorts to the full, canonical path of the file, so it will refer not only the relative path, but the entire structure from the file system root on:

```java
reference = '/home/paulo/a/bar.tex' // true
reference = 'a/bar.tex'             // false
```

So, the easy way to circumvent this situation is to replace `file` by `reference` and it should work. However, some experts (citation needed) do not recommend running TeX-related tools in such fashion. It seems the better way is to enter the directory structure, compile the file from within and run for your lives!

So, we could take a different route. We could, _in theory_, add a new directive option to our engines named `directory`. The name is, of course, self-explanatory. In our example:

```tex
% : arara: pdftex: { directory: 'a', files: [ 'bar.tex' ] }
...
```
Observe that `files` correspond to a list of files within our directory.

The implementation is quite straightforward. I thought something along these lines:

```java
if (isEmpty(directory)) {
    return getCommand('pdflatex', interaction, draft, shell,
           synctex, options, file);
}
else {
    return getCommandWithWorkingDirectory(directory, 'pdflatex',
           interaction, draft, shell, synctex, options, file);
}
```

We already are prepared for such move, thanks to the obscure yet useful `getCommandWithWorkingDirectory` helper method. :wink: 

Thoughts?

**Comment by nlct** [comment]
I like the idea, but I think there should be an added restriction so that you can change down to a sub-directory but not up, outside of the directory that `foo.tex` lives in.

**Comment by cereda** [comment]
Nicky, interesting idea. Since I had to fix #128 (and finally increase our major revision counter), I took the opportunity to implement a rule method named `isSubdirectory(File directory)` for exactly this purpose. The idea is to take the original reference (i.e, the main file in the project, the one supplied to `arara`) and check if the parent canonical path is a prefix of the provided directory. In my preliminary tests, it seems to work. I updated the user manual accordingly (commit yet to be pushed), so I think we can now implement the `directory` option.

Question: which rules should we apply this directory idea?

**Comment by cereda** [comment]
Hi @rmfberlin, thanks for your message!

By the looks of it, `arara` is picking up the default `xelatex` rule instead of yours. Did you create a (global or project-based) configuration file and set the rule path for `arara` to find your custom `xelatex` rule? We might need some information regarding your project structure, but in general lines, if you have

```
.
├── chapters
│   └── ...
├── main.tex
└── xelatex.yaml
```
You need to create a configuration file `arararc.yaml` (this is one of the four possible names) in that level

```
.
├── arararc.yaml
├── chapters
│   └── ...
├── main.tex
└── xelatex.yaml
```

with the following content:

```yaml
!config
paths:
- '.'
```

Hope it helps!

**Comment by rmfberlin** [comment]
Yes, I did so how you recommended. arara is now using the local rule xelatex.yaml. I get the same error message:
<blockquote>I have spotted an error in rule 'xelatex' located at '/Users/webmaster/Documents/08_Buecher/082_bin-ich-bereit/.'. I found these unknown keys in the directive: (directory).</blockquote>

If I commented out arara: directory: directory-name

I got this error message:
<blockquote> I have spotted an error in rule 'xelatex' located at
'/Users/webmaster/Documents/08_Buecher/082_bin-ich-bereit/.'. I
could not evaluate one of the provided commands. This part is
quite tricky, since it involves aspects of the underlying
expression language...

DETAILS ---------------------------------------------------------
[Error: unresolvable property or identifier: directory]
[Near :
{... if (isEmpty(directory)) { ....}]
</blockquote>

**Comment by cereda** [comment]
@rmfberlin now that I noticed it: your rule does not have the `directory` option defined in the `arguments` section, so `arara` will complain.

It's not exactly what we are planning for this option, but here's a quick fix for your rule. Please add it to the end of it:

```yaml
- identifier: directory
  flag: >
    @{
        return parameters.directory;
    }
```

Hope it works now.

**Comment by nlct** [comment]
> Question: which rules should we apply this directory idea?

I think it should only be possible to change to sub-directories (relative to the file containing the directive, `foo.tex` in your example). Imagine some naughty person deciding to sneak a directive into some shared code that changes to the user's home directory and started deleting essential files.

At the UK TUG meeting last year I demonstrated two ways of destroying the contents of a file: the first with TeX's native I/O and the second using the shell escape to (mis)use a trusted application. A similar method could be implemented with arara. The damage if this was done would be far greater if arara was allowed to change to an arbitrary directory.

(Me with my paranoid hat on :wink:  )

**Comment by cereda** [comment]
@nlct Nicky, I managed to implement a method for this (yet to commit), so we are both wearing our paranoid hats. :wink: Should we go for all engines and perhaps all bibliography tools?

**Comment by nlct** [comment]
> Should we go for all engines and perhaps all bibliography tools?

Yes, and indexing tools. Perhaps we also ought to allow changing to `TEXMFOUTPUT`.

**Comment by cereda** [comment]
@nlct I will tidy up the code and update some messages, so we can close #128 first. Then we can think of what to do next. :wink:

**Comment by rmfberlin** [comment]
Yes, it works! Thanks a lot!

**Comment by rmfberlin** [comment]
> @rmfberlin now that I noticed it: your rule does not have the `directory` option defined in the `arguments` section, so `arara` will complain.
> 
> It's not exactly what we are planning for this option, but here's a quick fix for your rule. Please add it to the end of it:
> 
> ```yaml
> - identifier: directory
>   flag: >
>     @{
>         return parameters.directory;
>     }
> ```
> 
> Hope it works now.
Yes, it works! Thanks a lot!

**Comment by TheTeXnician** [comment]
arara v5.0 will feature a working directory option, so you can run `arara -d /home/alpha/paulo/test file.tex`. This will resolve all directives against the working directory. arara v5.0 will be released prior to the DANTE Frühjahrstagung (end of the month).
