### ISSUE TITLE
if missing('pdf') - unknown keys in the directive? 

### ISSUE THREAD

**Issue by rmfberlin** [cereda/arara#129]
In the head of my master tex-file I wrote:

% arara: xelatex: {
% arara: --> shell: yes,
% arara: --> synctex: yes,
% arara: --> if missing('pdf')
% arara: --> || changed('tex'),
% arara: --> files: [ file01.tex, file02.tex, file03.tex ]
% arara: --> }

I got this error message:
I have spotted an error in rule 'xelatex' located at '/usr/local/texlive/2019/texmf-dist/scripts/arara/rules'. I found these unknown keys in the directive: (if missing('pdf') || changed('tex')).

How could I fix this?
Best regards
Rainer

System:
arara 4.0 (revision 1)!
arara @ /usr/local/texlive/2019/texmf-dist/scripts/arara
Java 12.0.2, Oracle Corporation
/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home
Mac OS X, x86_64, 10.14.6

**Comment by cereda** [comment]
Hi @rmfberlin!

The conditional should be outside the parameter map, so the correct syntax would be:

```
% arara: xelatex: {
% arara: --> shell: yes,
% arara: --> synctex: yes,
% arara: --> files: [ file01.tex, file02.tex, file03.tex ]
% arara: --> }
% arara: --> if missing('pdf')
% arara: --> || changed('tex')
```

Unless of course you are trying to set up conditional options, which is something that `arara` does not support. The conditionals are only supported for directives as atomic units.

Hope it helps!

**Comment by cereda** [comment]
I suppose this issue is fixed, then I will close it. :wink:
