### ISSUE TITLE
'Cannot create property=identifier' with even the most basic custom rule file

### ISSUE THREAD

**Issue by fmatter** [cereda/arara#130]
I used [this](https://tex.stackexchange.com/questions/440172/new-version-of-arara-broke-my-custom-rule) example rule, since my own attempt at writing a rule had failed (as had another, probably pre-4.0 rule).

However, I am still getting the following error:

```
I could not parse the configuration file, something bad happened.
Apparently, the provided YAML file is invalid. I will do my best
to help you in any way I can. There are more details available on
this exception:

DETAILS ---------------------------------------------------------
Cannot create property=identifier for
JavaBean=com.github.cereda.arara.model.Resource@340f438e
 in
'reader', line 1, column 1:
    !config
    ^
Unable to find
property 'identifier' on class:
com.github.cereda.arara.model.Resource
 in 'reader', line 2,
column 13:
    identifier: ls
```

The name of the file is `araraconfig.yaml`, which `arara` seems to recognize.

System: macOS Sierra, TeX Live 2019, `arara` 4.0.6

**Comment by cereda** [comment]
Hi! What's the full content of your `araraconfig.yaml`? Note that this file is the configuration file, not a rule. :wink:

**Comment by fmatter** [comment]
> Hi! What's the full content of your `araraconfig.yaml`? Note that this file is the configuration file, not a rule. 😉

duh! Thanks. All good, for now :)

**Comment by cereda** [comment]
Phew, I was worried for a minute. :wink: Please poke me if you need any explanation.

**Comment by fmatter** [comment]
More informed cry for help [on TeX SE](https://tex.stackexchange.com/questions/508788/render-separate-pdfs-for-every-chapter-with-arara) :)

**Comment by cereda** [comment]
Sure thing!
