### ISSUE TITLE
"official" rule for engine-dev

### ISSUE THREAD

**Issue by pablgonz** [cereda/arara#132]
Hello, now that it's possible to use the development versions, you can add an "official" rule for `pdflatex-dev`, something like that:
```tex
% arara: pdflatex-dev: { interaction: batchmode }
\documentclass{article}
\begin{document}
Hola Paulo, gracias por crear arara :)
\end{document}
```
Saludos

**Comment by cereda** [comment]
¡Hola, Pablo! :wink: 

Thank you very much for the suggestion! Since we need to update the engines to incorporate the `directory` option (#127), @nlct and I thought we could include a `branch` option as well, such that

```tex
% arara: pdflatex: { interaction: batchmode, branch: experimental }
```

would invoke `pdflatex-dev` instead of `pdflatex`. Similarly, using `stable` as `branch` option would bring us the default engine call. :wink: 

Any thoughts?

Saludos, amigo!

Paulo

**Comment by pablgonz** [comment]
Thank you for answering so quickly, maybe a shorter name:
```tex
% arara: pdflatex: { interaction: batchmode, branch: developer }
```
Perhaps it is a good idea to implement in CLI an option for this too, so we could check the differences if there are differences when running `pdflatex` and `pdflatex-dev` without having to modify the "rule" in the source file. Something like:
```bash
-b,--branch developer
-b,--branch experimental
```
I know that arara has the `--preamble` option that could fulfill this function, but, as a user it is more comfortable to do it from the command line :).

**Comment by cereda** [comment]
Hi Pablo, sorry for the delay in replying. The last few days have been hectic!

I think the key value could hold some synonyms (as these values would be set in the rule scope), so `experimental`, `development` and `developer` could all be valid entries. :wink: 

Regarding the CLI, although I am a bit reticent on adding specific purpose options, I've been discussing with the team the possibility of a new _system properties CLI support_. So we could have

```bash
$ arara test.tex -Dbranch=developer
```

which would set a `branch` property/variable in the rule scope to hold the `developer` value (or something along these lines). Of course, this is just a rough sketch, but that's the idea. :wink: 

Now, I just need to find time to finally update the rules (and the manual) accordingly. It will happen sooner or later. :wink: 

Cheerio!

Paulo

**Comment by pablgonz** [comment]
Great, as far as CLI is concerned, I was only saying that for those users who use git to save files `.tex` to be modifying the rule to test the differences between `pdflatex-dev` and `pdflatex` would make changes in the source files and by forgetting they would go in some commit.
```
arara test.tex -Dbranch=developer
```
That would be enough :)
Thanks again.
Greetings
Pablo

**Comment by cereda** [comment]
Pablo, if you don't mind, I would like to keep this issue open as a reminder for me to work on the development branch alongside with #127. :wink:

**Comment by TheTeXnician** [comment]
arara v5.0 will feature an extended rule set with more engines and all available engines having a `branch` option. The release is scheduled to happen before the DANTE Frühjahrstagung.
