### ISSUE TITLE
Possible new rule for biber

### ISSUE THREAD

**Issue by eg9** [cereda/arara#136]
If one wants to run `biber` with the `-tool` option, the standard `biber` rules will fail, because the input file has to be 

See https://tex.stackexchange.com/q/528240/4427 with Ulrike Fischer's analysis and my attempt at implementing a different rule.

I'm not sure that arara can distinguish whether among the options there is `--tool` and, in this case omit `getBasename(file)` from the command to run. If this is possible, then a new rule would not be needed. Note that the input file for `biber` is a `.bib` file, rather than `.bcf`, in this case when `--tool` is used.

In the new rule, passing the `--tool` option should perhaps be implicit.

**Comment by cereda** [comment]
Thank you very much, Enrico! I propose the following rule:

```yaml
!config
identifier: biber
name: Biber
authors:
- Marco Daniel
- Paulo Cereda
commands:
- name: The Biber reference management software
  command: >
    @{
        if (tool) {
            return getCommand('biber', '--tool', options);
        }
        else {
            return getCommand('biber', options, getBasename(file));
        }
    }
arguments:
- identifier: tool
  flag: >
    @{
      return isTrue(parameters.tool);
    }
  default: >
    @{
      return false;
    }
- identifier: options
  flag: >
    @{
        if (isList(parameters.options)) {
            return parameters.options;
        }
        else {
            throwError('I was expecting a list of options.');
        }
    }
```

It seems to work like a charm with the provided MWE. Grazie!

**Comment by TheTeXnician** [comment]
arara v5.0 will feature an extended biber rule as suggested by Paulo. The release is scheduled to happen before the DANTE Frühjahrstagung.
