### ISSUE TITLE
arara-manual.pdf missing from ‘Releases’ assets

### ISSUE THREAD

**Issue by galexite** [cereda/arara#137]
In the release description for 4.0, this manual is mentioned along with a checksum but it isn’t attached as far as I can work out.

**Comment by cereda** [comment]
Hello George!

Thank you very much for spotting this. I really don't know what happened. When I edited the _release_ field, I noticed the following notification:

![Quack](https://user-images.githubusercontent.com/302062/75135559-aa5aac00-56c0-11ea-96bb-7d41495f30a6.png)

So, for reasons unknown, `arara-manual.pdf` seemed to be corrupted over time!

I fixed the file, so everything seems to be in place. :wink:

Thank you again for your report!

Cheerio,

Paulo

**Comment by galexite** [comment]
No problem, how strange! Thank you for fixing this!
