### ISSUE TITLE
Arara does not kill underlying processes when stopped from Latex-Workshop VSCode extension

### ISSUE THREAD

**Issue by BambOoxX** [cereda/arara#138]
Currently using `arara` within the Latex-Workshop extension of VSCode, when killing the compilation process using the appropriate switch, some underlying `java` and `tex` programs are left running.

This issue is related to [this one](https://github.com/James-Yu/LaTeX-Workshop/issues/1996) opened on the Latex-Workshop tracker. According to people there it is in `arara` scope to solve this. 

Any ideas, why it happens ? In fact this problem does not show up when using `arara` from the terminal. By the way the same issue happens when using the Atom-Latex extension on Atom.

**Comment by cereda** [comment]
Hi!

Thank you for the report! We will investigate the issue. Which operating system do you use?

Cheerio!

**Comment by BambOoxX** [comment]
@cereda thanks, I am using Win10 with miktex.

**Comment by cereda** [comment]
Ace! We will investigate!

**Comment by TheTeXnician** [comment]
The team have come to the the conclusion that `arara` does what it should, viz. leaving low-level process management to the JVM and the operating system. Currently, `arara` relies on the lower layers having a clue about process layout and child relationship and we do not intend to change the behavior in version 5.

For version 6 (estimate: TL 2021), we are investigating possible safe guards to terminate child processes on `SIGTERM` in the course of major changes to the execution logic.

(cc @cereda)

**Comment by TheTeXnician** [comment]
To follow the version 6 milestone will now be tracked at our main issue tracker on GitLab as https://gitlab.com/islandoftex/arara/-/issues/39. Hence, it will be closed here.

**Comment by BambOoxX** [comment]
@TheTeXnician Thanks for the fast reaction. However, I must admit I'm a little lost. I am very musing using `arara` dumb style ^^ . Could you elaborate your answer with respect to the one in the VSCode extension tracker [here](https://github.com/James-Yu/LaTeX-Workshop/issues/1996#issuecomment-602182416) ?

**Comment by TheTeXnician** [comment]
`arara` does not do its own process management. It creates processes using the instructions provided by the JVM which in turn delegates some aspects of process management to the operating system. We consider `arara` to be stateless regarding processes, it does not know it has started a process once the process is running as child process.

Processes can be terminated in a number of ways. If `arara` terminates successfully, it does so by returning control to the calling process. If it fails, idem. The only problem in between is when a process like TeX is waiting for input and `arara` is in interactive mode. Then `arara` waits for input as well. Now you (or your editor or its plugins) may terminate `arara` forcefully (using e.g. `SIGTERM` or `SIGKILL`).

We have no clue about the plugin you are using and are not using VS Code personally. But irrespective of the editor and plugin solution the team shares the same position on `arara`'s process management:

* The proper way to kill a running TeX process that is waiting for input is to insert `x`. `arara` will detect the non-zero exit code and exit. This is what should be possible in every editor when running `arara` interactively.
* It is not `arara`'s job (in version 5) to track processes as this is more low-level and `arara` understands itself as automation tool to create the processes for you. As they are running in linear order and running interactively, `arara` is not managing them, the user is.
* `arara` will have to keep track of running processes in version 6, so we give up on the “stateless” nature. Hence, we will consider to do the child process cleanup job when `arara` receives `SIGTERM`. That is what is tracked in the GitLab issue.

I hope these points make it a bit more clear what the team's position is. If there is any clear evidence that it should be `arara`'s job to manage processes, we are willing to reconsider adding this in a future minor release of v5. But currently, it is a long-term consideration.

**Comment by BambOoxX** [comment]
@TheTeXnician Thanks for the precisions. I will discuss this with the guys handling the VSCode extension.

**Comment by cereda** [comment]
@BambOoxX thank you very much for your patience. :wink: 

As @TheTeXnician says, process handling is indeed tricky and involves a lot of variables. We will keep an eye on how `arara` is behaving and see what can be done on our side. :wink:

**Comment by BambOoxX** [comment]
@cereda I totally agree with you. Thanks for the help !

**Comment by BambOoxX** [comment]
@cereda @TheTeXnician I searched a bit more this issue in the related issue on the LaTeX-Workshop tracker. Could you please have a look at my last comment to see if this goes in the right direction? https://github.com/James-Yu/LaTeX-Workshop/issues/1996#issuecomment-629628960. 

Thanks for any help !

**Comment by BambOoxX** [comment]
@cereda @TheTeXnician I more or less documented some precautions to take when using `arara` and LaTeX-Workshop together in https://github.com/James-Yu/LaTeX-Workshop/issues/2139. I will try to add this information in the official wiki of LaTeX-Workshop. Would you be willing to document this in the `arara` manual too, or is it not relevant in this context ?
