### ISSUE TITLE
Localisation issue

### ISSUE THREAD

**Issue by sergeyulyanov** [cereda/arara#33]
Hi Paolo!

I have a question related to the localization of `arara`.

If I specify the output language with the flag `--language lang` then `arara` displays messages according to the encoding specified in the JVM system variable `file.encoding`.
However, the encoding of the console or IDE output may differ from it.
For example, in my system default console encoding is utf-8 but `file.encoding` variable is set to MacCyrillic. In this case, the localized messages are displayed incorrectly in console output.

As a workaround, I can change the encoding of the terminal in accordance with the `file.encoding` variable or vice versa by export `JAVA_TOOL_OPTIONS` variable with `-Dfile.encoding=my_console_encoding` value before call the `arara`. Another simple way is to use a system variables in wrapper script, such as: 

``` bash
#!/bin/bash
jarpath=`kpsewhich --progname=arara --format=texmfscripts arara.jar`
java -Dfile.encoding=$LANG -jar "$jarpath" "$@"
```

It seems to me that this is not quite correct.
A more flexible way in my opinion would be that the `arara` will automatically detect the encoding of the output stream and displays messages properly.

What do you think about this? Thank you.

**Comment by cereda** [comment]
Looks like the new JVM implementations have better encoding support (not to mention UTF-8 aware operating systems), so I think we have a good scenario for version 4.0 of `arara`. I will close this issue, but we can reopen it at any time. Cheerio! :wink:
