### ISSUE TITLE
Rules in local repository

### ISSUE THREAD

**Issue by drozzy** [cereda/arara#48]
Would be nice if arara read the `yaml` rule files in the same directory as my `tex` files.
For example, if I have a `book` git repo, I might want to commit a `biblatex.yaml` rule.
I would want arara to automatically pick up that rule and use it (instead of me going to some config file and adding `home/projects/blah/blah/book` to the search path).
Local rule files should also override global rule files.

Or is there a reason against this?

**Comment by cereda** [comment]
This is now possible due to the local configuration feature. Soon to be documented in the user manual, and hopefully the new `arara` will be released in June. Cheerio!
