### ISSUE TITLE
New rule for ImageMagick's `convert`

### ISSUE THREAD

**Issue by vermiculus** [cereda/arara#51]
It would be exceptional if the distribution came standard with rules to work with [`convert`](http://www.imagemagick.org/script/convert.php). When I get some free time early tomorrow, I'll work on chipping in the actual rule (or more likely _a starting point_) for this. For now though, I should be limiting my exposure to computers. :smile:

**Comment by TheTeXnician** [comment]
As of version 5.0 we are tracking all our rule set feature requests at https://gitlab.com/islandoftex/arara/-/issues/10. We are trying to reach rule set completion for that issue in version 5.1, so @cereda will be tackling `convert` in the next months :wink:

To reduce the number of duplicate issues, this will be closed in favor of the GitLab issue.
