### ISSUE TITLE
Migrating from  arara 3 to arara 4

### ISSUE THREAD

**Issue by petobens** [cereda/arara#64]
Hi Paulo, I'm trying to use the new arara 4 but I'm having some trouble. With arara 3 I can use the following directive:

      % arara: pdflatex: {action: batchmode, draft: yes, options: "-file-line-error -max-print-line=120"}

How am I suppose to translate it to arara 4? 

   I tried to migrate starting with an even simpler directive:

    % arara: pdflatex: {action: batchmode}

which with arara 4 I believe is:

    % arara: pdflatex: {interaction: batchmode}

but I get an error:

    I can't find file `batchmode`. 

Thanks in advance for the help.

**Comment by cereda** [comment]
Hello! `:)`

Oh my, you've spotted a bug in the engine rules! I've provided a fix for them (3ec9d02fe12020f20d9a9ca2f2f146a33f1cb1fd), hopefully the `interaction` parameter now works as expected. Thanks for the report! `:)`

Regarding the `options` parameter, it now requires a list instead of a long string, so

```tex
% arara: pdflatex: { options: "-file-line-error -max-print-line=120" }
```

should become

```tex
% arara: pdflatex: { options: [ "-file-line-error", "-max-print-line=120" ] }
```

Each option is an element of this list. `:)`

Thanks a million for the feedback!

All the best,

Paulo

**Comment by petobens** [comment]
@cereda  thanks for the quick fix! Now it works great. I really like the multiline support.

I found one additional problem (probably because I'm doing something wrong). If I use the `clean` rule, for instanace  like this:

    % arara: pdflatex: {interaction: nonstopmode,
    % arara: --> options: [ "-file-line-error", "-max-print-line=120" ]}
    % arara: clean: {files: [foo.aux, foo.log]}

arara will open both `foo.aux` and `foo.log`  instead of erasing them. (I don't know if this is relevant but I'm on Windows)

Thanks again for the previous quick fix.

**Comment by cereda** [comment]
@petobens Oh my, yet another bug! `:)` I'm almost sure I spotted that earlier, but I forgot to fix it. Now it should work as expected.

Have fun!

**Comment by petobens** [comment]
@cereda  Thanks for yet another quick fix. Now everything works as expected. If you want I can close this issue. However, if you don't mind, I prefer to leave it open for a few days because I will probably be asking you further questions regarding the usage of the amazing arara 4 (especially conditionals).

**Comment by cereda** [comment]
@petobens Sure thing. `:)` How's the impression so far?

**Comment by petobens** [comment]
From what I tested: directives are way cleaner now and arara seems (and I believe is) much more powerful. In one word: awesome!

**Comment by cereda** [comment]
@petobens Thanks for the kind words. `:)` By the way, we have a dedicated [Gitter chatroom](https://gitter.im/cereda/arara) for talking about `arara`. You are more than welcome to join us! `:)`

**Comment by petobens** [comment]
Thanks for the chat invitation. I asked a small question there. If you don't mind I prefer to ask a few more specific questions here ( since I can't figure out how to write a markdown code block there and the questions might be quite specific).

**Comment by cereda** [comment]
@petobens No worries. `:)`

**Comment by vermiculus** [comment]
@petobens Long-time gitter user here. To the far right of the chat input box, there are little chat bubbles. If you hover, the tooltip reads "compose mode" and then its keyboard shortcut. You can click this to toggle between compose / chat mode.

The easiest way to do it though is begin your message with three backticks `` ``` `` and then press enter – gitter will automatically switch to compose mode. after that, you can delete the backticks and write your message.

Feel free to use my [test repository's chatroom](https://gitter.im/vermiculus/test) to play around.

**Comment by petobens** [comment]
@vermiculus  thanks for explaining how to use it (I fell pretty stupid now that I now that I see those chat bubbles which I hadn't noticed before).  I'll do some tests in your test chatroom. :smile:

**Comment by petobens** [comment]
Hi @cereda. What's the best way to only run `biber` if it is really necessary?
Assuming that checking the log file for the warning `Please (re)run Biber on the file` is the (one) proper way to do it,  the following works:

    % arara: biber if found('log', 'run Biber on the file')

However I would like to write the full warning in the regex, but none of the following work:

    % arara: biber if found('log', 'Please (re)run Biber on the file')
    % arara: biber if found('log', 'Please \(re\)run Biber on the file')

Thanks in advance for the help.

**Comment by cereda** [comment]
@petobens Escaping parenthesis in an inline Java code would require two backslashes, so

```tex
% arara: biber if found('log', 'Please \\(re\\)run Biber on the file')
```

might work (untested, I'm writing these lines based on the compiler inside my head). `:)`

Now, about a better way of doing this check: I have no idea. `:)` That's the beauty (and danger) of conditionals, they can be used as one's heart desires.

**Comment by petobens** [comment]
Thanks @cereda,  using

    % arara: biber if found('log', 'Please \\(re\\)run Biber on the file') 

works great (I'm sorry I didn't figure that out myself, I know very little java). 

I think now I'm almost done migrating from arara 3. I have just two more questions (sorry for being such a nuisance):

i) Why is it that the 
 
    --------------------------------------------------------- FAILURE

message is given immediately after the error itself? (this can be seen in the image below). It is possible to get that message in a new line? .The reason I ask this is that I use vim errorformat to parse the shell output for errors and display them in the quickfix window. Instead of displaying the error as 

     foo.tex|6 error| Undefined control sequence

I get 

    foo.tex|6 error| Undefined control sequence--------------------------------------------------------- FAILURE

I understand that this is probably not a priority but since arara4 hasn't been released into the wild yet and this is something that is bothering me since arara 3 I thought maybe you could do something about it. I obviously understand if you don't. 

![screenshot-03-03-2015_21-03-39](https://cloud.githubusercontent.com/assets/2583971/6475568/86852cd0-c1ea-11e4-8691-a0688be730a7.png)

ii) As it can also be seen in previous the image, I built arara4 with maven and run it from the jar file. How can I get and exe file as the one provided with arara3?. I read about `Launch4j` but maybe you can suggest another way.

Once again thanks Paulo for all the great help and sorry for all the questions.

**Comment by cereda** [comment]
@petobens No worries about the escaping, I'm writing a tool for users, not developers. `:)` Your doubt is very important, I should make a note in the manual when covering methods with regex-based parameters.

Also, do not be sorry about questions, please! I need your feedback! `:)` We do not have a great userbase by chance, we do care about everybody, that's the whole point. `:)`

Regarding the layout, I tried the very same setup in my machine and got the correct output:

```bash
[paulo@cambridge arara] $ java -jar arara.jar test.tex -v
  __ _ _ __ __ _ _ __ __ _ 
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing 'test.tex' (size: 179 bytes, last modified: 03/03/2015
22:46:23), please wait.

-----------------------------------------------------------------
(PDFLaTeX) PDFLaTeX engine
-----------------------------------------------------------------
pdflatex: unrecognized option '-max-print-line=120'
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
--------------------------------------------------------- FAILURE

Total: 0.34 seconds
```

Could you try running the very same file in the command line prompt, so we can make sure it's not localized (as `arara` is being called inside vim)? Sometimes, editors do strange things, and I suspect the associated [Errorformat](http://vim.wikia.com/wiki/Errorformats) could be improved towards this issue instead of us handling in our end. Sadly, I'm not so sure how to fix that either. `:(` But let us try to understand what's going on first, shall we? `:)`

If I recall correctly, you could do a naughty trick and get `arara.exe` and put in the same directory of your `arara.jar` file (considering you've renamed `arara-4.0-jar-with-dependencies.jar` to `arara.jar`); `arara.exe` is just a wrapper to `arara.jar` and it will look for this file in the same directory, so renaming the `.jar` file and copying the `.exe` file to the same level should suffice.

Speaking of vim, I hereby allocate you to the official `arara` vim team, congrats! This team was founded just now (ah the beauty of being the lead developer). `:P`

**Comment by cereda** [comment]
@petobens By the way, if you think you ask a lot of questions, you will love Marco Daniel. `:P`

**Comment by petobens** [comment]
I'm glad you don't mind me asking many questions :)

The trick of putting `arara.exe` in the same directory as  `arara.jar` worked beautifully!! :+1: 

Regarding the layout, I tried running in both in the command prompt and in powershell and I still get the "wrong" output (as seen in the images below). I think the problem is not with `-max-print-line` but with the `-file-line-error` option (by removing that option I get the same output as you). Can you set this option and check the output? 

Thanks for including me in the new official arara team. It's an honour. :P

![screenshot-03-03-2015_23-57-22](https://cloud.githubusercontent.com/assets/2583971/6477408/5680b7da-c202-11e4-9d93-9d07869fd6e9.png)
![screenshot-04-03-2015_00-03-54](https://cloud.githubusercontent.com/assets/2583971/6477409/56864b46-c202-11e4-8587-7af7d99497bd.png)

**Comment by cereda** [comment]
Hi Pedro, here we go once again! `:)` (sorry for the intrusive question, your name suggests a Portuguese/Hispanic ascendance, are you located nearby, maybe in South America? We might be neighbours!)

Glad to hear `arara.exe` works, I always forget about this devilish Windows things. `:)` The `.exe` file is actually a wrapper which calls `java` from your default JVM providing the corresponding `.jar` and parameters. There was an option to pack the `.jar` file inside the `.exe` as well, but I decided to keep things simpler. The TeX Live wrapper works almost the same way, it seems it's a good trend. `:)`

Now, to the layout business: still no reproducible in here, sady. I think we are now considering two options:

- let's blame the Windows process handler, or
- let's blame the Windows version of PDFLaTeX. `:)`

Could you try adding `--log` to your execution and check the very same layout in the resulting `arara.log` file? If the layout is broken there as well, we can blame the underlying process handler or the Windows binaries.

By any chance, do you have TeX Live in your Windows machine? It would also be interesting to check if this layout issue also happens with the TL binary.

In any case, I can easily add an extra line after the long result information (I already took a peek at my code and checked what has to be done, it's just one line insertion), but my OCD is hitting me pretty hard on this matter. `:)`

Again, no problem in adding an extra line, I just want to make sure we know exactly why we are adding it to the code. `:)`

All the best!

**Comment by petobens** [comment]
Hello Paulo. We can be considered neighbors  since I live in Argentina.

Regarding the layout, it doesn't seem broken in the `arara.log`. Given a `foo.tex` in my Desktop that looks like this:

    \documentclass{article}
    % arara: pdflatex: {interaction: batchmode, draft: yes,
    % arara: --> options: ["-file-line-error"]}
    \begin{document}
    \error
    \end{document}

if I run `arara -v -l foo.tex` I get the following `arara.log`:

    04 Mar 2015 10:00:10.710 INFO  - Welcome to arara 4.0!
    04 Mar 2015 10:00:10.710 INFO  - -----------------------------------------------------------------
    04 Mar 2015 10:00:10.710 INFO  - ::: Java 1.8.0_31, Oracle Corporation
    04 Mar 2015 10:00:10.710 INFO  - ::: C:\Program Files\Java\jre1.8.0_31
    04 Mar 2015 10:00:10.710 INFO  - ::: Windows 8.1, amd64, 6.3
    04 Mar 2015 10:00:10.710 INFO  - -----------------------------------------------------------------
    04 Mar 2015 10:00:10.710 INFO  - Processing 'foo.tex' (size: 163 bytes, last modified: 03/04/2015 10:00:03), please wait.
    04 Mar 2015 10:00:10.710 INFO  - I found a potential pattern in line 2: pdflatex: {interaction: batchmode, draft: yes,
    04 Mar 2015 10:00:10.710 INFO  - I found a potential pattern in line 3: --> options: ["-file-line-error"]}
    04 Mar 2015 10:00:10.788 INFO  - I found a potential directive: Directive: { identifier: pdflatex, parameters: {interaction=batchmode, draft=yes, options=[-file-line-error]}, conditional: { NONE }, lines: [2, 3] }
    04 Mar 2015 10:00:10.788 INFO  - All directives were validated. We are good to go.
    04 Mar 2015 10:00:10.788 INFO  - -------------------------- DIRECTIVES ---------------------------
    04 Mar 2015 10:00:10.788 INFO  - Directive: { identifier: pdflatex, parameters: {interaction=batchmode, draft=yes, options=[-file-line-error], file=foo.tex, reference=C:\Users\Pedro\Desktop\foo.tex}, conditional: { NONE }, lines: [2, 3] }
    04 Mar 2015 10:00:10.788 INFO  - -----------------------------------------------------------------
    04 Mar 2015 10:00:10.788 INFO  - I am ready to interpret rule 'pdflatex'.
    04 Mar 2015 10:00:10.788 INFO  - Rule location: 'C:\OD\unix-tools\arara4\rules'
    04 Mar 2015 10:00:10.913 INFO  - I am ready to interpret task 'PDFLaTeX engine' from rule 'PDFLaTeX'.
    04 Mar 2015 10:00:10.913 INFO  - System command: [ pdflatex, --interaction=batchmode, --draftmode, -file-line-error, foo.tex ]
    04 Mar 2015 10:00:11.038 INFO  - ---------------------- BEGIN OUTPUT BUFFER ----------------------
    04 Mar 2015 10:00:11.038 INFO  - This is pdfTeX, Version 3.14159265-2.6-1.40.15 (MiKTeX 2.9)
    entering extended mode
    foo.tex:5: Undefined control sequence
    04 Mar 2015 10:00:11.038 INFO  - ----------------------- END OUTPUT BUFFER -----------------------
    04 Mar 2015 10:00:11.038 INFO  - Task result: FAILURE
    04 Mar 2015 10:00:11.038 INFO  - Total: 0.25 seconds

while the cmd prompt still gives:

![untitled](https://cloud.githubusercontent.com/assets/2583971/6484003/70977254-c256-11e4-904f-d5f167c89fa6.png)

Unfortunately I don't have Tex Live on my Windows machine so I cannot test it using the TL binary.

No idea if you can do something about it but if you can't just ignore this minor issue (in the end it is nothing more than an insignificant annoyance).

**Comment by cereda** [comment]
Pedro, it looks it's something related to the process handler + engine. Could you try every step again with this custom [`arara.jar` build](https://app.box.com/s/gp39sng2yeys7cwx59o35hg94p9rdq0d)? I added a new line in this build just for us to diagnose what's going on (or see if a new line might ease the impact of this layout issue).

**Comment by petobens** [comment]
With the new build the layout problem seems to be fixed!

![untitled](https://cloud.githubusercontent.com/assets/2583971/6485194/b5c64a62-c260-11e4-8ad4-84f07d4d7990.png)

and the `arara.log` seems fine:

    04 Mar 2015 11:20:26.681 INFO  - Welcome to arara 4.0!
    04 Mar 2015 11:20:26.684 INFO  - -----------------------------------------------------------------
    04 Mar 2015 11:20:26.686 INFO  - ::: Java 1.8.0_31, Oracle Corporation
    04 Mar 2015 11:20:26.686 INFO  - ::: C:\Program Files\Java\jre1.8.0_31
    04 Mar 2015 11:20:26.686 INFO  - ::: Windows 8.1, amd64, 6.3
    04 Mar 2015 11:20:26.686 INFO  - -----------------------------------------------------------------
    04 Mar 2015 11:20:26.686 INFO  - Processing 'foo.tex' (size: 175 bytes, last modified: 03/04/2015 10:02:55), please wait.
    04 Mar 2015 11:20:26.692 INFO  - I found a potential pattern in line 2: pdflatex: {interaction: batchmode, draft: yes,
    04 Mar 2015 11:20:26.692 INFO  - I found a potential pattern in line 3: --> options: ["-file-line-error"]}
    04 Mar 2015 11:20:26.746 INFO  - I found a potential directive: Directive: { identifier: pdflatex, parameters: {interaction=batchmode, draft=yes, options=[-file-line-error]}, conditional: { NONE }, lines: [2, 3] }
    04 Mar 2015 11:20:26.747 INFO  - All directives were validated. We are good to go.
    04 Mar 2015 11:20:26.747 INFO  - -------------------------- DIRECTIVES ---------------------------
    04 Mar 2015 11:20:26.747 INFO  - Directive: { identifier: pdflatex, parameters: {interaction=batchmode, draft=yes, options=[-file-line-error], file=foo.tex, reference=C:\Users\Pedro\Desktop\foo.tex}, conditional: { NONE }, lines: [2, 3] }
    04 Mar 2015 11:20:26.747 INFO  - -----------------------------------------------------------------
    04 Mar 2015 11:20:26.748 INFO  - I am ready to interpret rule 'pdflatex'.
    04 Mar 2015 11:20:26.749 INFO  - Rule location: 'C:\OD\unix-tools\arara4\rules'
    04 Mar 2015 11:20:26.888 INFO  - I am ready to interpret task 'PDFLaTeX engine' from rule 'PDFLaTeX'.
    04 Mar 2015 11:20:26.888 INFO  - System command: [ pdflatex, --interaction=batchmode, --draftmode, -file-line-error, foo.tex ]
    04 Mar 2015 11:20:27.002 INFO  - ---------------------- BEGIN OUTPUT BUFFER ----------------------
    04 Mar 2015 11:20:27.002 INFO  - This is pdfTeX, Version 3.14159265-2.6-1.40.15 (MiKTeX 2.9)
    entering extended mode
    foo.tex:5: Undefined control sequence
    04 Mar 2015 11:20:27.002 INFO  - ----------------------- END OUTPUT BUFFER -----------------------
    04 Mar 2015 11:20:27.005 INFO  - Task result: FAILURE
    04 Mar 2015 11:20:27.008 INFO  - Total: 0.26 sec

**Comment by cereda** [comment]
![I surrender to the bacteria](https://cloud.githubusercontent.com/assets/302062/6485848/5d32d294-c265-11e4-8129-b3fa649694b7.gif)

The new line has been added to the production code (per 79f54c81ae18e913daf245c6168c6fdde45dafbe). Personally, it's not my cup of tea (OCD thing), but I see no harm in a potential blank line before the long entry result. The logging output should not be affected and things should remain the same. `:)`

**Comment by petobens** [comment]
Thank you so much Paulo for doing that change! And thanks in general for all the great help and for creating such an amazing and powerful tool.

 I will close this issue since everything works marvelously now.

**Comment by cereda** [comment]
Great to hear everything is working like a charm! `:)` I suppose you are enjoying the new version? `:)`

**Comment by petobens** [comment]
I love the new version. Especially because I can do this:

	% arara: pdflatex: {interaction: batchmode, draft: yes,
	% arara: --> options: ["-file-line-error", "-max-print-line=120"]}
	% arara: biber if found('log', 'Please \\\\(re\\\\)run Biber on the file')
	% arara: pdflatex: {interaction: batchmode, draft: yes,
	% arara: --> options: ["-file-line-error", "-max-print-line=120"]}
	% arara: --> if found('log', 'Please \\\\(re\\\\)run Biber on the file')
	% arara: pdflatex: {interaction: nonstopmode, synctex: yes,
	% arara: --> options: ["-file-line-error", "-max-print-line=120"]}

Maybe I can still optimize the number of runs but for the time being I'm really happy with the above sequence. Thank you very much.

**Comment by cereda** [comment]
My pleasure, you guys are the reason for this new awesome version. :heart: Community surely matters.

**Comment by petobens** [comment]
:smile:
