### ISSUE TITLE
Save and use same compilation/directive sequence 

### ISSUE THREAD

**Issue by petobens** [cereda/arara#65]
Hi Paulo @cereda ,

After reading your comment [here](https://github.com/cereda/arara/issues/34#issuecomment-87697226)  I think that what I want to achieve can already be done with arara 4 (i.e is not a local configuration file). Basically on every tex file I add:

```tex
% arara: pdflatex: {interaction: batchmode, synctex: yes,
% arara: --> options: ["-file-line-error", "-max-print-line=120"]}
% arara: biber if found('log', 'Please \\(re\\)run Biber on the file')
% arara: --> && found('bcf', 'citekey')
% arara: pdflatex: {interaction: batchmode, synctex: yes,
% arara: --> options: ["-file-line-error", "-max-print-line=120"]}
% arara: --> if found('log', 'Please \\(re\\)run Biber on the file')
% arara: --> && found('bcf', 'citekey')
% arara: pdflatex: {interaction: batchmode, synctex: yes,
% arara: --> options: ["-file-line-error", "-max-print-line=120"]}
% arara: --> if found('log', '(undefined references|Please rerun|Rerun to get)')
```

I was wondering if I could somehow save this compilation/directive sequence in `arararc.yaml` and then in my documents only write:

```tex
% arara: my_compilation_sequence
```

which can eventually be followed by other directives, such as:
```tex
% arara: my_compilation_sequence
% arara: clean: {files: [foo.aux, foo.log]}
```

Is this possible? Thanks in advance!

**Comment by cereda** [comment]
Hello Pedro. `:)`

Sadly, what you want to achieve is not currently possible with `arara` 4.0, but you actually gave me an idea. Here we go.

First things first: I'm not fond of `my_compilation_sequence` to act as a single directive since it is, in essence, a collection of directives. Besides, at that level, all directives are already computed, so I'm not sure it will be easy to expand things.

Now, check this: I could offer a `--preamble` flag to `arara` in which you could point to a batch of directives from the configuration file. This is just a sample from my sandbox:

```yaml
preambles:
  twopdflatexes: |
    % arara: pdflatex
    % arara: pdflatex
```

This `preambles` key would be a new entry in the configuration file and it's basically a map - users would be able to add as many batches of directives as their hearts desire. In the example, `twopdflatexes` is the key mapped to those two `arara` directives invoking `pdflatex`. A call to

```bash
$ arara --preamble twopdflatexes test.tex
```

would correspond to

```tex
% from twopdflatexes preamble

% arara: pdflatex
% arara: pdflatex

% the content of test.tex
...
```

In the directive level, it would be quite complicated to parse `twopdflatexes` because directives were already computed. I think that would the best I could offer.

How does it sound?

All the best!

**Comment by petobens** [comment]
So basically I would be able to do 

    $ arara --preamble my_compilation_sequence test.tex

and obtain 

    % arara: pdflatex: {interaction: batchmode, synctex: yes,
    % arara: --> options: ["-file-line-error", "-max-print-line=120"]}
    % arara: biber if found('log', 'Please \\(re\\)run Biber on the file')
    % arara: --> && found('bcf', 'citekey')
    % arara: pdflatex: {interaction: batchmode, synctex: yes,
    % arara: --> options: ["-file-line-error", "-max-print-line=120"]}
    % arara: --> if found('log', 'Please \\(re\\)run Biber on the file')
    % arara: --> && found('bcf', 'citekey')
    % arara: pdflatex: {interaction: batchmode, synctex: yes,
    % arara: --> options: ["-file-line-error", "-max-print-line=120"]}
    % arara: --> if found('log', '(undefined references|Please rerun|Rerun to get)')

where `my_compilation_sequence` is defined in in the configuation file as

    preambles:
      my_compilation_sequence: |
        % arara: pdflatex ...

?

If that's the case (i.e if I understood correctly), it sounds marvelously.

**Comment by cereda** [comment]
Yes, that would be my plan. `:)` But it's only brainstorming for now, I need to implement it. `:)`

**Comment by petobens** [comment]
No need to implement this ASAP. Thanks for the kind support! :)

**Comment by cereda** [comment]
Implemented. `:)`

**Comment by cereda** [comment]
Pedro, if you want to test it, I have a release right here: https://app.box.com/s/uh9zsgwvwyau5ihiepn8j7qhkquk2ofd

Some quick instructions: This is a sample code from my configuration file:

```yaml
!config
preambles:
  runtex: |
    % arara: pdftex
    % arara: pdftex
```

where `runtex` is the key associated to the following content. To use this preamble, just use

```bash
$ arara --preamble runtex file.tex
```

or

```bash
$ arara -p runtex file.tex
```

> @nlct and @marcodaniel: I had to include two new localized messages, `INFO_PARSER_PREAMBLE_DESCRIPTION` and `ERROR_PARSER_INVALID_PREAMBLE`; I took the liberty of including them in your localized files, when you have some spare time, could you please update them? Thanks, friends. `:)`

**Comment by cereda** [comment]
I rewrote the preamble lookup routine, nothing major, just an OCD requirement. `:)`

**Comment by petobens** [comment]
Hi Paulo, 

That was fast!!!

I've built the latest version but I'm having trouble getting this to work. My config file (`C:\Users\Pedro\arararc.yaml`) is:

```yaml
!config
preambles:
    minimize_runs: |
        % arara: pdflatex: {interaction: batchmode, synctex: yes,
        % arara: --> options: ["-file-line-error", "-max-print-line=120"]}
        % arara: biber if found('log', 'Please \\(re\\)run Biber on the file')
        % arara: --> && found('bcf', 'citekey')
        % arara: pdflatex: {interaction: batchmode, synctex: yes,
        % arara: --> options: ["-file-line-error", "-max-print-line=120"]}
        % arara: --> if found('log', 'Please \\(re\\)run Biber on the file')
        % arara: --> && found('bcf', 'citekey')
        % arara: pdflatex: {interaction: batchmode, synctex: yes,
        % arara: --> options: ["-file-line-error", "-max-print-line=120"]}
        % arara: --> if found('log', '(undefined references|Please rerun|Rerun to get)')
```
However when I run `arara -p minimize_runs foo.tex`, I get the following error:

![screenshot-31-03-2015_11-50-46](https://cloud.githubusercontent.com/assets/2583971/6921590/32570620-d79c-11e4-8e25-827b5100fa4b.png)

What is it that I'm doing wrong? Thanks in advance for the help.!

**Comment by cereda** [comment]
Pedro, things work on my end. Could we talk in the Gitter chatroom? I think it's easier for us to debug what's going on. `:)`

https://gitter.im/cereda/arara

**Comment by cereda** [comment]
Pedro, I tried a sample execution in my dad's Windows PC (yay, dad!) and everything worked as expected:

![screen](https://cloud.githubusercontent.com/assets/302062/6922416/51fbbba6-d7a1-11e4-82de-24caa10f6660.png)

So let's add the specific operating system issue to the bottom of our list of hypotheses. `:)`

I am almost sure there is a clash of configuration files (you might have other configuration files which are being selected instead the one you want). I updated the code to include a new line in the log file indicating which configuration file was picked during the current run, so it might help you debug what's going on.

**Comment by petobens** [comment]
@cereda  I'm a bit short of time until the evening. As soon as I get a chance to try it out I''ll let you know. Thanks as always for your awesome support.

**Comment by petobens** [comment]
Paulo, 

You were, obviously, right. My symlink from my home directory to the arara config file in my dotfiles directory was broken. After fixing it this new feature works like a charm. 
I'm so happy that I can now forget about the whole (manual) compilation process and let arara handle it for me.

Thank you once again!!

**Comment by cereda** [comment]
Glad it worked. `:)` Thanks for the suggestion, it was fun implementing it. `:)`

**Comment by petobens** [comment]
Hi Paulo,

Thanks for telling me about the possibility of project-specific preambles.

One minor question. As you can see in my config file I always run pdflatex like this

```tex
        % arara: pdflatex: {interaction: batchmode, synctex: yes,
        % arara: --> options: ["-file-line-error", "-max-print-line=120"]}
```
and check if we need biber runs like this:
```tex
if found('log', 'Please \\(re\\)run Biber on the file') && found('bcf', 'citekey')
```

So I was wondering if I can I somehow specify in my rc file something like 

```yaml
mypdflatex = {interaction: batchmode, synctex: yes, options: ["-file-line-error", "-max-print-line=120"]}
need_biber = found('log', 'Please \\(re\\)run Biber on the file') && found('bcf', 'citekey')
```
and then write the `minimize_runs` directive sequence  like:

```tex
% arara: mypdflatex 
% arara: biber if need_biber
% arara: mypdflatex if need_biber
% arara: mypdflatex if found('log', '(undefined references|Please rerun|Rerun to get)')
```

**Comment by cereda** [comment]
Hi Pedro!

No, it's not possible (and it would be tricky to implement). I'm sorry `:(`

One for the future releases, I guess. `:)`

**Comment by petobens** [comment]
No problem Paulo :)
I only thought that if this could be done then the rc code would be a bit cleaner. But it works great the way it is!

Again thanks for implementing this feature! :):)
