### ISSUE TITLE
Extract directives only in the file header

### ISSUE THREAD

**Issue by cereda** [cereda/arara#73]
It would be interesting to include a feature in which `arara` only extract directives in the file header, that is, before the actual content. :smile:

**Comment by cereda** [comment]
![anchorman-well-that-escalated-quickly](https://cloud.githubusercontent.com/assets/302062/10050854/ba219c90-61f4-11e5-95ec-c56da1ec9a12.jpg)

**Comment by vermiculus** [comment]
http://i.imgur.com/lGIoMpb.gif

**Comment by cereda** [comment]
We are wacky! :smile:
