### ISSUE TITLE
Allow file globbing/list of files to compile

### ISSUE THREAD

**Issue by NobbZ** [cereda/arara#74]
A user in a german support board asked how he could compile multiple files as he was used to it from `latexmk` (`latexmk *.tex` does compile all texfiles in the current dir). We told him that it is not currently possible, but I do think that it would be a huge addition to arara to make this possible.

I do know about the differences about handling the asterisk on commandline by windows and unixoids, so I do know, that it will be a little bit harder under windows, because you need to resolve the glob by yourself there, but under unixoid operating systems it should be as easy as iterating over a list of sourcefiles.

**Comment by AndrewSwann** [comment]
`latexmk` with no argument does just that - compile all `.tex` files in the directory.

**Comment by NobbZ** [comment]
Still, the user wants to work with ``arara``, and that is missing such a feature.

**Comment by NobbZ** [comment]
Just for the sake of completeness a link to the corresponding thread:

[original](http://texwelt.de/wissen/fragen/14732/wie-kann-ich-mit-arara-alle-tex-dateien-in-einem-verzeichnis-kompilieren) and [google translated](https://translate.google.com/translate?sl=de&tl=en&js=y&prev=_t&hl=de&ie=UTF-8&u=http%3A%2F%2Ftexwelt.de%2Fwissen%2Ffragen%2F14732%2Fwie-kann-ich-mit-arara-alle-tex-dateien-in-einem-verzeichnis-kompilieren&edit-text=)

**Comment by AndrewSwann** [comment]
Sorry  - I misread your post.  Such a feature for `arara` would be a good idea.

**Comment by cereda** [comment]
Hi, friends!

Indeed, it would be an interesting feature. :smile: To be honest, I always imagined `arara` to handle one file at a time, but I believe users could benefit from handling several files at once.

I tried the following code:

```java
public class TestArgs {

    public static void main(String[] args) {
        int counter = 1;
        for (String arg : args) {
            System.out.println(counter + " --> " + arg);
            counter++;
        }
    }

}
```

The output I got:

```bash
[paulo@cambridge ~] $ find . -maxdepth 1 -type f
./b.txt
./TestArgs.java
./TestArgs.class
./a.txt
./c.tex
[paulo@cambridge ~] $ java TestArgs *.txt
1 --> a.txt
2 --> b.txt
[paulo@cambridge ~] $ java TestArgs *.t*
1 --> a.txt
2 --> b.txt
3 --> c.tex
```

I don't have a Windows virtual machine right now, but if this behaviour holds, I think the implementation would be straightforward. I will take a closer look later on today, once my dad lets me use his computer. I am still waiting a budget to get my VMware/Parallels license. :smile:

**Comment by NobbZ** [comment]
This behavior does not hold for windows, windows does pipe through the
asterisk as is. I already stated that in my initial post.

Paulo Cereda <notifications@github.com> schrieb am Fr., 09.10.2015, 14:52:

**Comment by cereda** [comment]
I thought there could be some JVM trickery, so my dad kindly let me test this code:

```bash
Microsoft Windows [versão 6.1.7601]

F:\>java TestArgs *.txt
1 --> a.txt
2 --> b.txt

F:\>java TestArgs *.t*
1 --> a.txt
2 --> b.txt
3 --> c.tex
```

So, it seems to work consistently. :smile: I need to check other versions.

**Comment by NobbZ** [comment]
Hasn't worked in XL though... I'll give it a try on on Win10 when home.

Paulo Cereda <notifications@github.com> schrieb am Fr., 09.10.2015, 15:25:

**Comment by cereda** [comment]
@NobbZ: Danke, Norbert. :smile:

**Comment by NobbZ** [comment]
Does work with win10 and Java 1.8.

Paulo Cereda <notifications@github.com> schrieb am Fr., 09.10.2015, 15:37:

**Comment by cereda** [comment]
Thank you, I will take a look at earlier versions of Windows and JVM, :wink:

**Comment by cereda** [comment]
New light on this issue! Up!

**Comment by TheTeXnician** [comment]
arara v5.0 will feature multi-file processing (as long as the files are within the same working directory). The release is scheduled to happen before the DANTE Frühjahrstagung.
