### ISSUE TITLE
Could not find the rule in the search path

### ISSUE THREAD

**Issue by drozzy** [cereda/arara#76]
This is odd, I am running Arara 3.0 installed on Windows 10.

Trying to run a file with simple `arara: pdflatex` directive at the top, I keep getting the: 

```
  __ _ _ __ __ _ _ __ __ _
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Uh-oh, I could not find the 'pdflatex' rule in the search path.
Could you take a look if the rule name is correct and if the rule
is accessible through the search path?
```

Error... I've added the arara dir to path, is there something else I must do?

**Comment by cereda** [comment]
This is indeed odd! How is `arara` installed in your system (TeX Live or standalone installer)?

When executed, `arara` finds its own path and determine the default rules location based on that information. It should work on 100% of the cases.

Could you list the content of the directory where `arara.jar` is located?

All the best! :wink:

**Comment by cereda** [comment]
Also, do you have any configuration file in your home directory? It is been a while since I dealt with an `arara` question, so I am a little rusty. :wink:

**Comment by drozzy** [comment]
Ok the problem was ... fixed. I think it was an outdated miketex install.

Thanks!
