### ISSUE TITLE
Disable the system LAF

### ISSUE THREAD

**Issue by cereda** [cereda/arara#90]
Friends, this is a very sensitive topic that I'd love your feedback. 😉 

As you all know, `arara` 4.0 features message boxes for user input (buttons, lists, text boxes, and so on). This is provided by the Swing widget toolkit.

Swing is known to be slower than, say, SWT (Standard Widget Toolkit, from Eclipse), but it is a pure Java approach rather than a wrapper to the native window manager. I like to favour Swing because I feel safer using it, even at the cost of some time for rendering.

That said, I would like to point you all to [this particular line](https://github.com/cereda/arara/blob/3beafedb216f910814079100405961ebc8967ff5/application/src/main/java/com/github/cereda/arara/utils/MessageUtils.java#L63). This might add a significant time for rendering in some JVM implementations (not counting the Swing rendering time). So I was wondering if we should disable the system LAF configuration and stick with the default widget rendering. In general, the first execution takes more time than subsequent executions. System LAF is more polished, so it gives a more receptive box than the (usually) ugly Swing ones.

It's also worth noting that it's possible to set up the system LAF via command line (in `java`, not `arara`). And personally I am not keen on adding an option in our configuration (or am I). 😉 

Thoughts?

Paulo

**Comment by egeerardyn** [comment]
Sensitive it is indeed 😄.

First, excuse me for possibly providing some clouds for the parade. I personally don't see the use for a GUI on a build tool (but that's one of the reasons I like to use Unix at times). A build tool should get out of my way, and that is exactly what a GUI doesn't do: it steals focus, it gets lost, ... But I might be the odd duck in that respect, since especially in Windows shops everything is expected to have a GUI (even a poor one).

When there is a GUI, however, I think it is quite important that it reacts in a way that is "native" to the OS your are using. This is two-fold: everything should look uniform, and all applications should ideally react according to the design language of the OS. Those are small things, but they go a long way towards a fluent user experience. If I had a cent for every time I grunted over some common shortcut such as Ctrl-A not working properly in an application (on whatever platform!), I would be rich.

That being said, if you really see a good use-case for a GUI (again, not my use case), and think the initial startup time is annoying, then it might be better to disable the native LaF by default if that can be tuned externally as well.

**Comment by cereda** [comment]
Thanks for the great feedback, Egon!

Thankfully, the GUI part is not an essential part of the tool (it's actually *very* optional). 😉  It just offers an user input in a more friendly way of interacting with the automation flow, say

```tex
% arara: makeglossaries if showOptions(2, 'Question!',
% arara: --> 'Do tell me, my good friend: should I create a glossary?',
% arara: --> 'Yes, please!', 'No way!') == 1
```

![Quack](https://cloud.githubusercontent.com/assets/302062/25194953/7e5a5962-2512-11e7-906a-de841e8b4efe.png)

*(GUI on my Fedora machine)*

In fact, the way I implemented these features, the rendering only happens if and only if there is any call to these GUI elements. Otherwise, `arara` behaves normally, with the usual startup time and no additional payload. So we are saved. 😉 

I also believe the more friendly the elements are, the easier will be for users to interact. So I think we are in the right track. The additional time only hits when these elements are used, but it does happen when `arara` is used the traditional way.

**Comment by egeerardyn** [comment]
Looks nice, I have to say. I agree with you that for some people it might offer a nice feature.

I wouldn't worry about the delay, as long as it is only a second or so (to put this in perspective, the last TeX document I worked on took about 10 seconds to compile (with a lot of effort to speed up the process; I think without that on a slow compiler it took about 20 minutes (still building the figures in parallel, though)).

**Comment by cereda** [comment]
Thanks, I might leave things as they are then. The idea of having these GUI elements is to provide some sort of didactic approach to the automation flow. Personally, I wouldn't use, but maybe one could use a set of directives during a course to make the student choose the right options in order to continue. 😉 

With these elements, the first execution takes more time than the subsequent ones, at least in my Linux box. But in my Mac, the time is very insignificant comparatively. Linux might be tricky due to other JVM vendors and implementations, and not to mention different window managers. But hey, it works! 🍷

**Comment by cereda** [comment]
![Mac](https://cloud.githubusercontent.com/assets/302062/25196805/29bad354-2518-11e7-9e7d-2f2244cb2b09.png)

I must admit, the rendering is *very* fast in my Mac, so I think it was just my usual paranoia striking back again. And do this window look *very* nice! Those Apple bastards... ❤️

**Comment by cereda** [comment]
Interesting, I thought I had closed this issue. I am probably getting more idiot as time goes by. :rofl: 

*Reference:* 8ff52e056bd0a49fc92ce053bfccb0283359931e

Now, `arara` uses the default LAF provided by the Swing toolkit. However, the configuration file now features a `laf` entry that allows overriding this behaviour, by providing the desired LAF full name. For example:

```yaml
laf: 'com.sun.java.swing.plaf.motif.MotifLookAndFeel'
```

This one is the Motif LAF provided by Java. Other styles can be used as well. As a shortcut, two special keywords as used to set up the LAF:

- `system`: this keyword makes the application rely on the system LAF (e.g, GTK+ in a typical Linux environment).
- `none`: *(default)* this keywork makes the application rely on the default LAF provided by the Swing toolkit.

When an invalid value is used (typo or inexistent LAF), the application gracefully fallback to the default LAF provided by the Swing toolkit. No error is generated.
