### ISSUE TITLE
handling found with non-existent file

### ISSUE THREAD

**Issue by samcarter8** [cereda/arara#91]
Not sure if this is a bug or a feature, but if I use the wonderful arara 4.0 to check if a file (not) contains a specific string using

`% arara: xelatex if !found('log', 'test')`

I will get an error if the file does not exist (for example for a new file during the first latex run, when the log file does not yet exist)

```
[Error: found('log', 'test'): I could not read the contents of
the file 'document.log', I got an IO error. I have no idea why it
failed, though. Perhaps the file was moved or deleted before or
during the reading operation. Or maybe I do not have the proper
permissions to read the file.]
[Near : {... @{ !found('log',
'test') } ....}]
             ^
[Line: 1, Column: 1] 
```

I know that I can catch this case using `exists`, but I was wondering if this is the intended behaviour.

**Comment by cereda** [comment]
It's been a while, but if I recall correctly, that's the intended behaviour of `found(...)`: raise an error if the file does not exist. It's a rather different behaviour from `changed(...)`, which gracefully handles inexistent files. 😉 

This is an important part that I plan to mention in the user manual: whenever possible, use *short circuit* to your advantage. In general, a conditional proposition can include logical conditions tied together with logical operators. When using `&&` in particular, this operator works on a short circuit basis, i.e, if I say `exists('foo') && found('foo','bar')`, in case `file.foo` does not exist, the logical evaluation won't proceed any further, as the first part was already false. So, `found('foo', 'bar')` is never executed and the error is not raised.

If possible, I recommend adding a `exists(...)` call first and `&&`. In case you need non-short circuiting operators, you can use `&` and `|`, if I recall them. :wink:

Thanks for the report, we can discuss any further this behaviour if you feel we could rethink the logic behind it. :wink:

**Comment by samcarter8** [comment]
Thanks for your reply and explanation! In combination with `exists` everything works fine, I was just wondering :)

**Comment by cereda** [comment]
My pleasure! Thanks for the great feedback, it's nice to know the new features are being used. 😉
