### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by ThomDietrich** [cereda/arara#98]
I'm very sorry if I overlooked something. In the README under [Basic Use](https://github.com/cereda/arara#basic-use) you say "You can read more ... in the manual". Please add a link to the manual right there. 😅 
I am a potential new user of arara and wanted to snoop around in the manual just to see if it is for me. However it is nowhere to be found. I had to download and start the arara setup to then tick "install manual" to finally find the manual in a random folder on system...

**Comment by cereda** [comment]
Hi Thomas, thank you very much for the feedback! I am far from my laptop, 
but I promise to fix this issue tomorrow, and also extend my comments 
regarding the documentation! For now, please accept my apologies, I will 
come back to you and this issue tomorrow.


A 8 de janeiro de 2018 9:04:11 PM, Thomas Dietrich 
<notifications@github.com> escreveu:

**Comment by ThomDietrich** [comment]
No need to apologize. I'm just humbly suggesting an improvement ;)

**Comment by cereda** [comment]
Hi Thomas! 😉 

I updated the `README.md` file with a link to the official user manual for version 3.0a available in CTAN. I also added a note for the (nonexistent) upcoming version 4.0 manual. Hopefully, newcomers aren't too much lost! 😄 

I might add some pointers on how TeX Live and MiKTeX users can browse the existing documentation by issuing `texdoc arara` in the terminal. However, I understand that not everybody likes those pesky text-only black screens. Wait a minute, `arara` *is* a terminal-based tool! Uh-oh... 😉 

I think I should blame my (lack of) `git` experience for messing with binary files in the past. In my defense, when the repository started, GitHub had much less features that it has today, so I need to catch up! For version 4.0, I was planning of a semi-automated documentation generation, in the lines of using tools like `asciidoc` or `sphinx` or even `pandoc` to provide web-friendly documents. One for the future, I guess.

Please, feel free to contact me at any time, I will be more than happy to help you! And thank you very much for giving `arara` a try! Make yourself at home!

Cheerio!

Paulo

**Comment by ThomDietrich** [comment]
Thanks for the quick "fix". Your future plans sound like a good idea! You could probably include an auto-generated pdf through bintray or similar...

Thanks for your help, hear you next time ;) Thomas
